
namespace MoriaDig;

// Contains mappings that describe how we extract the data from the game assets
internal class Mappings
{
    public static List<Mapping> ItemsMapping =
    [
        new("Type", "$.ResultItemHandle.RowName", Dig.ItemSplit1),
        new("Id", "$.ResultItemHandle.RowName", Dig.ItemSplit2),
        new("Name", "$.DisplayName.SourceString", Dig.Simple, Linked: true),
        new("Stations", "$.CraftingStations[*].RowName", Dig.NameLookup),
        new("Quantity", "$.ResultItemCount", Dig.Simple),
        new("CraftTime", "$.CraftTimeSeconds", Dig.Simple),
        new("CampaignSupport", "$.DefaultRequiredConstructions[*].RowName", Dig.NameLookup),
        new("CampaignMats", "$.DefaultRequiredMaterials", Dig.MaterialsLookup),
        new("EnabledState", "$.EnabledState", Dig.Simple),
        new("UnlockType", "$.DefaultUnlocks.UnlockType", Dig.Simple),
        new("UnlockNumFragments", "$.DefaultUnlocks.NumFragments", Dig.Simple, Condition: "UnlockType = \"EMorRecipeUnlockType::CollectFragments\""),
        new("UnlockRequiredFragments", "$.DefaultUnlocks.UnlockRequiredFragments[*].RowName", Dig.SimpleArray, Condition: "UnlockType = \"EMorRecipeUnlockType::CollectFragments\""),
        new("UnlockRequiredItems", "$.DefaultUnlocks.UnlockRequiredItems[*].RowName", Dig.NameLookup, Condition: "UnlockType = \"EMorRecipeUnlockType::DiscoverDependencies\""),
        new("UnlockRequiredConstructions", "$.DefaultUnlocks.UnlockRequiredConstructions[*].RowName", Dig.NameLookup, Condition: "UnlockType = \"EMorRecipeUnlockType::DiscoverDependencies\""),
        new("bHasSandboxRequirementsOverride", "$.bHasSandboxRequirementsOverride", Dig.Simple, Excluded: true),
        new("bHasSandboxUnlockOverride", "$.bHasSandboxUnlockOverride", Dig.Simple, Excluded: true),
        new("SandboxSupport", "$.SandboxRequiredConstructions[*].RowName", Dig.NameLookup, Condition: "bHasSandboxRequirementsOverride = \"True\""),
        new("SandboxMats", "$.SandboxRequiredMaterials", Dig.MaterialsLookup, Condition: "bHasSandboxRequirementsOverride = \"True\""),
        new("SandboxUnlockType", "$.SandboxUnlocks.UnlockType", Dig.Simple, Condition: "bHasSandboxUnlockOverride = \"True\""),
        new("SandboxUnlockNumFragments", "$.SandboxUnlocks.NumFragments", Dig.Simple, Condition: "bHasSandboxUnlockOverride = \"True\" and SandboxUnlockType = \"EMorRecipeUnlockType::CollectFragments\""),
        new("SandboxUnlockRequiredFragments", "$.SandboxUnlocks.UnlockRequiredFragments[*].RowName", Dig.SimpleArray, Condition: "bHasSandboxUnlockOverride = \"True\" and SandboxUnlockType = \"EMorRecipeUnlockType::CollectFragments\""),
        new("SandboxUnlockRequiredItems", "$.SandboxUnlocks.UnlockRequiredItems[*].RowName", Dig.NameLookup, Condition: "bHasSandboxUnlockOverride = \"True\""),
        new("SandboxUnlockRequiredConstructions", "$.SandboxUnlocks.UnlockRequiredConstructions[*].RowName", Dig.NameLookup, Condition: "bHasSandboxUnlockOverride = \"True\""),
        new("SpoilageSeconds", "$.SpoilageSeconds", Dig.Simple, Linked: true),
        new("HungerRestore", "$.HungerRestore", Dig.Simple, Linked: true),
        new("HealthRestore", "$.HealthRestore", Dig.Simple, Linked: true),
        new("EnergyRestore", "$.EnergyRestore", Dig.Simple, Linked: true),
        new("MaxStackSize", "$.MaxStackSize", Dig.Simple, Linked: true),
        //new("SlotSize", "$.SlotSize", Dig.Simple, Linked: true),
        new("Durability", "$.Durability", Dig.Simple, Linked: true),
        new("DamageReduction", "$.DamageReduction", Dig.Simple, Linked: true),
        new("DamageProtection", "$.DamageProtection", Dig.Simple, Linked: true),
        new("MealTime", "$.MealTime", Dig.Simple, Linked: true),
        //new("ItemHotbarBehavior", "$.ItemHotbarBehavior", Dig.Simple, Linked: true),
        new("InitialRepairCost", "$.InitialRepairCost", Dig.MaterialsLookup, Linked: true),
        //new("DamageModifiers", "$.DamageModifiers[*].RowName", Dig.SimpleArray, Linked: true),
        //new("UseEffects", "$.UseEffects[*].ObjectPath", Dig.SimpleArray, Linked: true),
        //new("MealTimeUseEffects", "$.MealTimeUseEffects[*].ObjectPath", Dig.SimpleArray, Linked: true),
        //new("VisibleEffects", "$.VisibleEffects[*].ObjectPath", Dig.SimpleArray, Linked: true),
        //new("EquipEffects", "$.EquipEffects[*].ObjectPath", Dig.SimpleArray, Linked: true),
        //new("HolsterEffects", "$.HolsterEffects[*].ObjectPath", Dig.SimpleArray, Linked: true),
        new("Description", "$.Description.SourceString", Dig.Simple, Linked: true),
        new("Icon", "$.Icon.AssetPathName", Dig.ExtractIcon, Linked: true),
    ];

    public static List<Mapping> BuildingsMapping =
    [
        new("Type", "Construction", Dig.Constant, Excluded: true),
        new("Id", "$.ResultConstructionHandle.RowName", Dig.Simple),
        new("Name", "$.DisplayName.SourceString", Dig.Simple, Linked: true),
        new("EnabledState", "$.EnabledState", Dig.Simple),
        //new("BuildProcess", "$.BuildProcess", Dig.Simple),
        new("LocationRequirement", "$.LocationRequirement", Dig.Simple),
        new("PlacementType", "$.PlacementType", Dig.Simple),
        new("bOnWall", "$.bOnWall", Dig.Simple),
        new("bOnFloor", "$.bOnFloor", Dig.Simple),
        new("bPlaceOnWater", "$.bPlaceOnWater", Dig.Simple),
        //new("bOverrideRotation", "$.bOverrideRotation", Dig.Simple),
        new("FoundationRule", "$.FoundationRule", Dig.Simple),
        new("bAutoFoundation", "$.bAutoFoundation", Dig.Simple),
        new("bInheritAutoFoundationStability", "$.bInheritAutoFoundationStability", Dig.Simple),
        new("bAllowRefunds", "$.bAllowRefunds", Dig.Simple),
        //new("CampaignSupport", "$.DefaultRequiredConstructions[*].RowName", Dig.NameLookup),
        new("CampaignMats", "$.DefaultRequiredMaterials", Dig.MaterialsLookup),
        new("UnlockType", "$.DefaultUnlocks.UnlockType", Dig.Simple),
        //new("UnlockNumFragments", "$.DefaultUnlocks.NumFragments", Dig.Simple, Condition: "UnlockType = \"EMorRecipeUnlockType::CollectFragments\""),
        //new("UnlockRequiredFragments", "$.DefaultUnlocks.UnlockRequiredFragments[*].RowName", Dig.SimpleArray, Condition: "UnlockType = \"EMorRecipeUnlockType::CollectFragments\""),
        new("UnlockRequiredItems", "$.DefaultUnlocks.UnlockRequiredItems[*].RowName", Dig.NameLookup, Condition: "UnlockType = \"EMorRecipeUnlockType::DiscoverDependencies\""),
        new("UnlockRequiredConstructions", "$.DefaultUnlocks.UnlockRequiredConstructions[*].RowName", Dig.NameLookup, Condition: "UnlockType = \"EMorRecipeUnlockType::DiscoverDependencies\""),
        new("bHasSandboxRequirementsOverride", "$.bHasSandboxRequirementsOverride", Dig.Simple, Excluded: true),
        new("bHasSandboxUnlockOverride", "$.bHasSandboxUnlockOverride", Dig.Simple, Excluded: true),
        //new("SandboxSupport", "$.SandboxRequiredConstructions[*].RowName", Dig.NameLookup, Condition: "bHasSandboxRequirementsOverride = \"True\""),
        new("SandboxMats", "$.SandboxRequiredMaterials", Dig.MaterialsLookup, Condition: "bHasSandboxRequirementsOverride = \"True\""),
        new("SandboxUnlockType", "$.SandboxUnlocks.UnlockType", Dig.Simple, Condition: "bHasSandboxUnlockOverride = \"True\""),
        //new("SandboxUnlockNumFragments", "$.SandboxUnlocks.NumFragments", Dig.Simple, Condition: "bHasSandboxUnlockOverride = \"True\" and SandboxUnlockType = \"EMorRecipeUnlockType::CollectFragments\""),
        //new("SandboxUnlockRequiredFragments", "$.SandboxUnlocks.UnlockRequiredFragments[*].RowName", Dig.SimpleArray, Condition: "bHasSandboxUnlockOverride = \"True\" and SandboxUnlockType = \"EMorRecipeUnlockType::CollectFragments\""),
        new("SandboxUnlockRequiredItems", "$.SandboxUnlocks.UnlockRequiredItems[*].RowName", Dig.NameLookup, Condition: "bHasSandboxUnlockOverride = \"True\""),
        new("SandboxUnlockRequiredConstructions", "$.SandboxUnlocks.UnlockRequiredConstructions[*].RowName", Dig.NameLookup, Condition: "bHasSandboxUnlockOverride = \"True\""),
        new("Description", "$.Description.SourceString", Dig.Simple, Linked: true),
        new("Icon", "$.Icon.ObjectPath", Dig.ExtractIcon, Linked: true),
    ];
}
